package com.xhuabu.source.model.po;

import java.util.Date;

public class AdminGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.group_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.admin_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.create_admin_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private Integer createAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.create_time
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.update_time
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_group.comment
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.id
     *
     * @return the value of admin_group.id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.id
     *
     * @param id the value for admin_group.id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.group_id
     *
     * @return the value of admin_group.group_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.group_id
     *
     * @param groupId the value for admin_group.group_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.admin_id
     *
     * @return the value of admin_group.admin_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.admin_id
     *
     * @param adminId the value for admin_group.admin_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.create_admin_id
     *
     * @return the value of admin_group.create_admin_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.create_admin_id
     *
     * @param createAdminId the value for admin_group.create_admin_id
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.create_time
     *
     * @return the value of admin_group.create_time
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.create_time
     *
     * @param createTime the value for admin_group.create_time
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.update_time
     *
     * @return the value of admin_group.update_time
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.update_time
     *
     * @param updateTime the value for admin_group.update_time
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_group.comment
     *
     * @return the value of admin_group.comment
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_group.comment
     *
     * @param comment the value for admin_group.comment
     *
     * @mbg.generated Tue Jun 05 22:13:21 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}