package com.xhuabu.source.model.po;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.id
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.nick_name
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.username
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.password
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.salt
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.phone
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.status
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.last_ip
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.last_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.comment
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.create_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.update_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.id
     *
     * @return the value of admins.id
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.id
     *
     * @param id the value for admins.id
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.nick_name
     *
     * @return the value of admins.nick_name
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.nick_name
     *
     * @param nickName the value for admins.nick_name
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.username
     *
     * @return the value of admins.username
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.username
     *
     * @param username the value for admins.username
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.password
     *
     * @return the value of admins.password
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.password
     *
     * @param password the value for admins.password
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.salt
     *
     * @return the value of admins.salt
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.salt
     *
     * @param salt the value for admins.salt
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.phone
     *
     * @return the value of admins.phone
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.phone
     *
     * @param phone the value for admins.phone
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.status
     *
     * @return the value of admins.status
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.status
     *
     * @param status the value for admins.status
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.last_ip
     *
     * @return the value of admins.last_ip
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.last_ip
     *
     * @param lastIp the value for admins.last_ip
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.last_time
     *
     * @return the value of admins.last_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.last_time
     *
     * @param lastTime the value for admins.last_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.comment
     *
     * @return the value of admins.comment
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.comment
     *
     * @param comment the value for admins.comment
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.create_time
     *
     * @return the value of admins.create_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.create_time
     *
     * @param createTime the value for admins.create_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.update_time
     *
     * @return the value of admins.update_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.update_time
     *
     * @param updateTime the value for admins.update_time
     *
     * @mbg.generated Tue Jun 05 21:55:43 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}