package com.xhuabu.source.model.po;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.update_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.nick_name
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.salt
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.status
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_ip
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.comment
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_admin_id
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    private Integer createAdminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.update_time
     *
     * @return the value of admin.update_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.update_time
     *
     * @param updateTime the value for admin.update_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.nick_name
     *
     * @return the value of admin.nick_name
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.nick_name
     *
     * @param nickName the value for admin.nick_name
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.salt
     *
     * @return the value of admin.salt
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.salt
     *
     * @param salt the value for admin.salt
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.status
     *
     * @return the value of admin.status
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.status
     *
     * @param status the value for admin.status
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_ip
     *
     * @return the value of admin.last_ip
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_ip
     *
     * @param lastIp the value for admin.last_ip
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.comment
     *
     * @return the value of admin.comment
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.comment
     *
     * @param comment the value for admin.comment
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_time
     *
     * @return the value of admin.last_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_time
     *
     * @param lastTime the value for admin.last_time
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_admin_id
     *
     * @return the value of admin.create_admin_id
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_admin_id
     *
     * @param createAdminId the value for admin.create_admin_id
     *
     * @mbg.generated Mon Jan 29 15:54:58 CST 2018
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }
}