package com.xhuabu.source.model.po;

import java.util.Date;

public class GroupMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.kid
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private String kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.group_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.menu_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.create_admin_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private Integer createAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.create_time
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.update_time
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_menu.comment
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.id
     *
     * @return the value of group_menu.id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.id
     *
     * @param id the value for group_menu.id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.kid
     *
     * @return the value of group_menu.kid
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public String getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.kid
     *
     * @param kid the value for group_menu.kid
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setKid(String kid) {
        this.kid = kid == null ? null : kid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.group_id
     *
     * @return the value of group_menu.group_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.group_id
     *
     * @param groupId the value for group_menu.group_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.menu_id
     *
     * @return the value of group_menu.menu_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.menu_id
     *
     * @param menuId the value for group_menu.menu_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.create_admin_id
     *
     * @return the value of group_menu.create_admin_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.create_admin_id
     *
     * @param createAdminId the value for group_menu.create_admin_id
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.create_time
     *
     * @return the value of group_menu.create_time
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.create_time
     *
     * @param createTime the value for group_menu.create_time
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.update_time
     *
     * @return the value of group_menu.update_time
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.update_time
     *
     * @param updateTime the value for group_menu.update_time
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_menu.comment
     *
     * @return the value of group_menu.comment
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_menu.comment
     *
     * @param comment the value for group_menu.comment
     *
     * @mbg.generated Wed Jul 11 17:08:55 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}