package com.xhuabu.source.model.po;

import java.util.Date;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.name
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.create_admin_id
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    private Integer createAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.create_time
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.update_time
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.comment
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.name
     *
     * @return the value of groups.name
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.name
     *
     * @param name the value for groups.name
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.create_admin_id
     *
     * @return the value of groups.create_admin_id
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.create_admin_id
     *
     * @param createAdminId the value for groups.create_admin_id
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.create_time
     *
     * @return the value of groups.create_time
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.create_time
     *
     * @param createTime the value for groups.create_time
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.update_time
     *
     * @return the value of groups.update_time
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.update_time
     *
     * @param updateTime the value for groups.update_time
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.comment
     *
     * @return the value of groups.comment
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.comment
     *
     * @param comment the value for groups.comment
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}