package com.xhuabu.source.model.po;

import java.util.Date;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_admin_id
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    private Integer createAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_time
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.update_time
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.comment
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.create_admin_id
     *
     * @return the value of group.create_admin_id
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.create_admin_id
     *
     * @param createAdminId the value for group.create_admin_id
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.create_time
     *
     * @return the value of group.create_time
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.create_time
     *
     * @param createTime the value for group.create_time
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.update_time
     *
     * @return the value of group.update_time
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.update_time
     *
     * @param updateTime the value for group.update_time
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.comment
     *
     * @return the value of group.comment
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.comment
     *
     * @param comment the value for group.comment
     *
     * @mbg.generated Sat Jul 07 23:56:18 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}