package com.xhuabu.source.dao;

import com.xhuabu.source.model.po.GroupAuth;
import com.xhuabu.source.model.po.GroupAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    long countByExample(GroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int deleteByExample(GroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int insert(GroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int insertSelective(GroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    List<GroupAuth> selectByExample(GroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    GroupAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") GroupAuth record, @Param("example") GroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int updateByExample(@Param("record") GroupAuth record, @Param("example") GroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int updateByPrimaryKeySelective(GroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_auth
     *
     * @mbg.generated Wed Dec 20 11:36:04 CST 2017
     */
    int updateByPrimaryKey(GroupAuth record);
}